name: Render and Deploy Dashboard

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 14 * * *"

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-action/setup@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            httr2
            jsonlite
            tidyverse
            scales

        name: Render dashboard
        run: |
          quarto render finalprojectdash.qmd --to html --output index.html
          mkdir -p_site
          mv index.html _site/index.html
